src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Ignore;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\DBAL\Types\Types;
use Serializable;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[Vich\Uploadable]
#[UniqueEntity(fields: ['email'], message: 'Il y a déjà un compte avec cet email !')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface, Serializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 125, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file = null;

    #[Vich\UploadableField(mapping: 'featured_profils', fileNameProperty: 'file')]  
    #[Assert\File(maxSize:'2M', maxSizeMessage:  'La taille du fichier ne doit pas dépasser 2 Mo.')]
    private $imageFile;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private ?string $resetToken;

    #[ORM\Column(type: 'datetime_immutable', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Subscription::class)]
    private Collection $subscriptions;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $stripeId = null;

    #[ORM\OneToMany(mappedBy: 'users', targetEntity: Posts::class)]
    private Collection $posts;

    #[ORM\OneToMany(mappedBy: 'users', targetEntity: Comments::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->subscriptions = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getImageFile(File $image = null)
    {
        return $this->imageFile;
    }

    public function setImageFile(File $image = null)
    {        
        $this->imageFile = $image;

         if($image) {
            $this->file = $image->getFilename();
             $this->updated_at = new \DateTime('now');
         }

    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(?bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
    
     /**
     * @return Collection<int, Subscription>
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function addSubscription(Subscription $subscription): self
    {
        if (!$this->subscriptions->contains($subscription)) {
            $this->subscriptions->add($subscription);
            $subscription->setUser($this);
        }

        return $this;
    }

    public function removeSubscription(Subscription $subscription): self
    {
        if ($this->subscriptions->removeElement($subscription)) {
            // set the owning side to null (unless already changed)
            if ($subscription->getUser() === $this) {
                $subscription->setUser(null);
            }
        }

        return $this;
    }

    public function hasActiveSubscription(): bool
    {
        foreach ($this->subscriptions as $subscription) {
            if ($subscription->isActive()) {
                return true; // L'utilisateur a au moins un abonnement actif
            }
        }

        return false; // Aucun abonnement actif trouvé
    }

    public function getStripeId(): ?string
    {
        return $this->stripeId;
    }

    public function setStripeId(?string $stripeId): self
    {
        $this->stripeId = $stripeId;

        return $this;
    }

    /**
     * @return Collection<int, Posts>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Posts $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUsers($this);
        }

        return $this;
    }

    public function removePost(Posts $post): static
    {
        if ($this->posts->removeElement($post)) {
            if ($post->getUsers() === $this) {
                $post->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUsers($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">

<head>
    {% block meta %}
    <!-- Required meta tags -->
    <!-- Canonic URL -->
    <link rel="canonical" href="{{ app.request.scheme ~ '://' ~ app.request.host ~ app.request.pathInfo }}">
    <!-- links for favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('V1/assets/favicon/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('V1/assets/favicon/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('V1/assets/favicon/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('V1/assets/favicon/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('V1/assets/favicon/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('V1/assets/favicon/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('V1/assets/favicon/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('V1/assets/favicon/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('V1/assets/favicon/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ asset('V1/assets/favicon/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('V1/assets/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('V1/assets/favicon/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('V1/assets/favicon/favicon-16x16.png') }}">
    {# <link rel="manifest" href="{{ asset('V1/assets/favicon/manifest.json') }}"> #}
    <meta name="msapplication-TileColor" content="#ffffff">
    {# <meta name="msapplication-TileImage" content="{{ asset('assets/favicon/ms-icon-144x144.png') }}"> #}
    <meta name="theme-color" content="#ffffff">
    <!-- Basic metas -->
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    <meta name="description" content="Besoin d’un site internet pro à Franconville ? SnapCode™ est votre agence web locale. Bénéficiez de 10 ans d’expertise pour un site rapide, moderne et 100% sur-mesure.">
    <meta name="keywords" content="">

    <!-- Mobile specific metas -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@SnapCode™">
    <meta name="twitter:creator" content="@SnapCode™">
    <meta name="twitter:title" content="SnapCode™">
    <meta name="twitter:description" content="SnapCode™ Digital Agency">
    <meta name="twitter:image" content="assets/images/brand-logo.svg">
    <!-- Facebook -->
    <meta property="og:url" content="">
    <meta property="og:title" content="SnapCode™">
    <meta property="og:description" content="SnapCode™ Digital Agency">
    <meta property="og:type" content="website">
    <meta property="og:image" content="assets/images/brand-logo.svg">
    <meta property="og:image:secure_url" content="">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    {% endblock %}
    <title>{% block title %}Agence Web à Franconville – Création de site internet | SnapCode™ Agency{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
    <!-- Icon fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,500i,700,700i,900" rel="stylesheet">

    <!-- css links -->

    <!-- Owl Carousel -->
    <link rel="stylesheet" type="text/css" href="{{ asset('V1/assets/css/vendor/owl.carousel.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('V1/assets/css/vendor/owl.theme.default.min.css') }}">

    <!-- Magnific popup -->
    <link rel="stylesheet" type="text/css" href="{{ asset('V1/assets/css/vendor/magnific-popup.css') }}">

    <!-- Custom styles -->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/style/style.css') }}">

    <!-- Load Flashy default CSS -->
    <link rel="stylesheet" href="{{ asset('./bundles/mercuryseriesflashy/css/flashy.css') }}">

    <!--Message Flash Icon-->
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- ICONS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% endblock %}
<!-- data test -->
<script
  defer
  data-website-id="6776ca8384c862c94194f0b2"
  data-domain="jeremiecode.fr"
  src="https://datafa.st/js/script.js">
</script>
</head>

<body>
    {% include 'header.html.twig' %}

    {% if app.user and app.user.isVerified == false %}
    <div class="flashy flashy--warning">
        <i class="material-icons">speaker_notes</i>
        <strong>Bonjour, {{app.user.prenom}}</strong>, <br> votre compte n'est pas encore activé. <br> Un lien d'activation vous a été envoyé par mail.<br>
        <a class="flashy__body" href="{{path('resend_verif')}}" target="_blank">Pas de lien ? <strong>Renvoyez le lien d'activation.</strong></a>
    </div>
    {% endif %}

    <main class="container" id="mainPage">
        {% block body %}{% endblock %}
    </main>

    <!-- Début de widget de badge Calendly -->
    <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
    <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
    <script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/ngoyi-jeremie-pro/appel-d-information-jeremiecode-1er-contact?hide_gdpr_banner=1', text: 'PRENDRE UN RDV', color: '#2A4DD0', textColor: '#ffffff', branding: undefined }); }</script>
    <!-- Fin de widget de badge Calendly -->

    {% include 'footer.html.twig' %}

    {% block javascripts %}
        <!-- jQuery -->
        {#<script src="{{ asset('assets/js/vendor/jquery.min.js') }}"></script>
        <script src="{{ asset('assets/js/vendor/jquery-migrate.min.js') }}"></script>#}
        <!-- Charger jQuery en premier -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        <!-- Charger le JavaScript de Bootstrap après jQuery -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <!-- jQuery Easing Plugin -->
        {#<script src="{{ asset('assets/js/vendor/easing-1.3.js') }}"></script>#}
        <!-- Magnific popup -->
        {#<script src="{{ asset('assets/js/vendor/jquery.magnific-popup.min.js') }}"></script>#}
        <!-- Custom Script -->
        <script src="{{ asset('assets/js/script.js') }}"></script>
        <!-- Load Flashy default JavaScript -->
        <script src="{{ asset('./bundles/mercuryseriesflashy/js/flashy.js') }}"></script>
    {% endblock %}
        <!-- Include Flashy default partial -->
        {{ include('@MercurySeriesFlashy/flashy.html.twig') }}
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                $(".my-alert").alert('my-close-button')
            });
        </script>
</body>

</html>

templates/base_error.html.twig
<!DOCTYPE html>
<html lang="fr" data-theme="auto">

<head>
    {% block meta %}
    <!-- Required meta tags -->
    <!-- links for favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('V1/assets/favicon/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('V1/assets/favicon/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('V1/assets/favicon/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('V1/assets/favicon/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('V1/assets/favicon/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('V1/assets/favicon/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('V1/assets/favicon/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('V1/assets/favicon/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('V1/assets/favicon/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ asset('V1/assets/favicon/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('V1/assets/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('V1/assets/favicon/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('V1/assets/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ asset('assets/favicon/manifest.json') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ asset('assets/favicon/ms-icon-144x144.png') }}">
    <meta name="theme-color" content="#ffffff">
    <!-- Basic metas -->
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Mobile specific metas -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@SnapCode™">
    <meta name="twitter:creator" content="@SnapCode™">
    <meta name="twitter:title" content="SnapCode™">
    <meta name="twitter:description" content="SnapCode™ Digital Agency">
    <meta name="twitter:image" content="assets/images/brand-logo.svg">
    <!-- Facebook -->
    <meta property="og:url" content="">
    <meta property="og:title" content="SnapCode™">
    <meta property="og:description" content="SnapCode™ Digital Agency">
    <meta property="og:type" content="website">
    <meta property="og:image" content="assets/images/brand-logo.svg">
    <meta property="og:image:secure_url" content="">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    {% endblock %}
    <title>{% block title %}SnapCode™ Agency{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
    <!-- Icon fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,500i,700,700i,900" rel="stylesheet">

    <!-- css links -->

    <!-- Owl Carousel -->
    <link rel="stylesheet" type="text/css" href="{{ asset('V1/assets/css/vendor/owl.carousel.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('V1/assets/css/vendor/owl.theme.default.min.css') }}">

    <!-- Magnific popup -->
    <link rel="stylesheet" type="text/css" href="{{ asset('V1/assets/css/vendor/magnific-popup.css') }}">

    <!-- Custom styles -->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/style/style.css') }}">

    <!-- Load Flashy default CSS -->
    <link rel="stylesheet" href="{{ asset('bundles/mercuryseriesflashy/css/flashy.css') }}">

    <!--Message Flash Icon-->
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- ICONS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% endblock %}

</head>

<body>
    {# {% include 'header_error.html.twig' %} #}

    <main class="container">
        {% block body %}{% endblock %}
    </main>

    {# {% include 'footer.html.twig' %} #}

    {% block javascripts %}
         <!-- jQuery -->
        <!-- Charger jQuery en premier -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        <!-- Charger le JavaScript de Bootstrap après jQuery -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <!-- Custom Script -->
        <script src="{{ asset('assets/js/script.js') }}"></script>
        <!-- Load Flashy default JavaScript -->
        <script src="{{ asset('./bundles/mercuryseriesflashy/js/flashy.js') }}"></script>
        <!-- Load Flashy default CSS -->
        <link rel="stylesheet" href="{{ asset('bundles/mercuryseriesflashy/css/flashy.css') }}">
    {% endblock %}
    <!-- Include Flashy default partial -->
    {{ include('@MercurySeriesFlashy/flashy.html.twig') }}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            $(".my-alert").alert('my-close-button')
        });
    </script>
</body>

</html>

templates/footer.html.twig
<footer class="footer-component">
    <div class="footer_content-wrapper">
        <div class="footer_cta">
            <div class="footer_logo-wrapper">
                <a href="{{path('app_home')}}" class="nav_logo-link w-nav-brand">
                    <img src="./assets/images/home/brand-logo.svg" loading="lazy" 
                    srcset="./assets/images/home/brand-logo.svg, 
                    ./assets/images/home/brand-logo.svg, 
                    ./assets/images/home/brand-logo.svg" alt="Logo SnapCode™ Agency transparent" class="nav_logo">
                </a>
            </div>
            <div class="foooter_cta-wrapper">
                <div class="footer_cta-title">Prêt à vous lancez ?</div>
                <div class="container_link_cta">
                    <a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/ngoyi-jeremie-pro/appel-d-information-jeremiecode-1er-contact?hide_gdpr_banner=1'});return false;">
                        <div class="container_cta">
                            <div class="button w-button">Prendre un RDV</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="w-layout-grid footer_grid">
            <address class="footer_links-list">
                <div class="footer_logo">Jérémie MAOLE</div>
                <div class="footer_copyright">Expert Développement Web<br>CEO SnapCode™ Agency</div>
                <a href="tel:+33661463480" class="footer_contact-link">+33 6 6* 4* 34 8*</a>
                <a href="mailto:contact@jeremiecode.fr" class="footer_contact-link">contact@jeremiecode.fr</a>
            </address>
            <div class="footer_links-list is--lower">
                <div class="footer_title">Informations</div>
                <a href="#a-propos" class="footer_link">À Propos</a>
                <a href="#realisations" class="footer_link">Mes Réalisations</a>
                <a href="#avis-clients" class="footer_link">Avis Clients</a>
                <a href="#tarifs" class="footer_link">Mes tarifs</a>
                <a href="#contact" class="footer_link">Contact</a>
                <a href="{{ path('blog_index') }}" class="footer_link">Blog</a>
            </div>
        </div>
        <div class="footer_bottom-content">
            <p class="footer_bottom-text">© 2019-<span id="year" class="footer_auto-year">2025</span> 
                <a href="/#" class="footer_home-link">
                    <span class="white-text">SnapCode™ Agency</span>
                </a>. Tous droits réservés. Designed by SnapCode™ Agency
            </p>
            <div class="footer_social-list">
                <a href="https://www.linkedin.com/in/jeremie-ngoyi-maole-366a41144/" target="_blank" class="footer_social-link-item w-inline-block">
                    <img src="https://assets-global.website-files.com/6533bdea645a5e7646167e3d/6533bdeb645a5e7646167f13_linkedin-icon.svg" alt="Icone linkedin" class="footer_social-icon">
                </a>
                <a href="https://www.malt.fr/profile/jeremiengoyi?overview" target="_blank" class="footer_social-link-item w-inline-block">
                    <img src="https://assets-global.website-files.com/6533bdea645a5e7646167e3d/6533ebc22845a4410ac2963e_malt-svgrepo-com.svg" width="24" alt="Icone Malt" class="footer_social-icon">
                </a>
                <a href="mailto:contact@jeremiecode.fr?subject=J'ai%20une%20question%20!%20" class="footer_social-link-item w-inline-block">
                    <img src="https://assets-global.website-files.com/6533bdea645a5e7646167e3d/6533bdeb645a5e7646167f14_icon-mail.svg" alt="Icone mail" class="footer_social-icon">
                </a>
            </div>
        </div>
    </div>
</footer>

templates/header_error.html.twig
<header class="page-header">
    <div class="container">
        <nav class="navbar navbar-expand-lg align-items-center navbar_error">
            <a class="navbar-brand" href="{{path('app_home')}}">
                <img src="./assets/images/home/brand-logo.svg" alt="SnapCode brand logo">
            </a>
            <!-- End of .navbar-brand -->
            <!-- End of .navbar-nav -->
        </nav>
    </div>
    <!-- End of .container -->
</header>